#!/usr/bin/env bash

# Copyright (c) 2022 xTekC.
# SPDX-License-Identifier: MPL-2.0

set -e

# Check the OS type
UNAME_OUT="$(uname -m)"

case "${UNAME_OUT}" in
    i686-unknown-linux-gnu)
        echo "Detected system: i686 Linux"
        ;;
    i686-unknown-linux-musl)
        echo "Detected system: i686 Linux musl"
        ;;
    x86_64-unknown-linux-gnu)
        echo "Detected system: x86_64 Linux"
        ;;
    x86_64-unknown-linux-musl)
        echo "Detected system: x86_64 Linux musl"
        ;;
    aarch64-unknown-linux-gnu)
        echo "Detected system: aarch64 Linux"
        ;;
    aarch64-unknown-linux-musl)
        echo "Detected system: aarch64 Linux musl"
        ;;
    riscv64gc-unknown-linux-gnu)
        echo "Detected system: riscv64gc Linux"
        ;;
    armv7-unknown-linux-gnueabihf)
        echo "Detected system: armv7 Linux"
        ;;
    x86_64-apple-darwin)
        echo "Detected system: x86_64 Mac"
        ;;
    aarch64-apple-darwin)
        echo "Detected system: aarch64 Mac"
        ;;
    *)
        echo "Detected system: UNKNOWN:${UNAME_OUT}"
        ;;
esac

echo "Detected operating system: ${UNAME_OUT}"

BIN_NAME="passgen"
BIN_VER="v0.1.0-39e3c92c"
BIN_AUTHOR="xTeKc"

echo Installing "$BIN_NAME"...

BIN_NAME_DIR=${BIN_NAME_DIR-"$HOME/.$BIN_NAME"}
BIN_NAME_BIN_DIR=$BIN_NAME_DIR/bin

BIN_URL="https://github.com/$BIN_AUTHOR/$BIN_NAME/releases/download/$BIN_VER/$BIN_NAME-$UNAME_OUT"
BIN_PATH="$BIN_NAME_BIN_DIR/$BIN_NAME"

# create .$BIN_NAME bin dir and $BIN_NAME bin if they don't exist
mkdir -p "$BIN_NAME_BIN_DIR"
curl -# -L "$BIN_URL" -o "$BIN_PATH"
chmod +x "$BIN_PATH"

# Store the correct profile file (i.e. .profile for Bash or .zshrc for ZSH).
case $SHELL in
*/zsh)
    PROFILE=$HOME/.zshrc
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*)
    echo "$BIN_NAME: could not detect shell, manually add ${BIN_NAME_BIN_DIR} to your PATH."
    exit 1
esac

# Only add $BIN_NAME if it isn't already in PATH.
if [[ ":$PATH:" != *":${BIN_NAME_BIN_DIR}:"* ]]; then
    # Add the $BIN_NAME directory to the path and ensure the old PATH variables remain.
    echo >> "$PROFILE" && echo "export PATH=\"\$PATH:$BIN_NAME_BIN_DIR\"" >> "$PROFILE"
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin && ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    printf "\n" && printf "warning: libusb not found. 
    You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi

printf "\n" && printf "Detected your preferred shell is "$PREF_SHELL" and added $BIN_NAME to PATH.
Run 'source "$PROFILE"' or start a new terminal session to use $BIN_NAME."